apiVersion: v1
kind: Service
metadata:
    name: shinobi-war-fairy-auth-api
    namespace: default
    labels:
        app: shinobi-war-fairy-auth-api
spec:
    type: ClusterIP
    ports:
        - port: 3002
          targetPort: http
          name: http
    selector:
        app: shinobi-war-fairy-auth-api
